### ISSUE TITLE
Waves-Core deployment

### ISSUE THREAD

**Issue by joanmarticarreras** [lirmm/waves-core#49]
Dear,

First and foremost, I'd like to congratulate you all for such a great tool! I just started to use it and in 16 hours I managed to have my pipeline in with little knowledge on Django.

Now I am trying to deploy the app to our department server, so everybody can access freely the service and do their queries to our server. This is proving to be a bit more challenging. Would it be possible for you to include a guide for deployment in Linux servers (p.e. Ubuntu 18.04 - Apache2) in your documentation?

Thank you very much and again, congratulations on your work.

~ Joan ~

**Comment by marcoooo** [comment]
As for the Apache documentation, since waves-core is a standard Django App, you can start by trying to follow this guide:
https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/modwsgi/

There is a sample wsgi file in here: https://github.com/lirmm/waves-core/blob/master/docs/waves_uwsgi.ini which you are free to reuse if necessary.

Another "easy" way is to use the Nginx/Gunicorn set up as well, may be less tricky than some Apache: https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/gunicorn/

**Comment by marcoooo** [comment]
Hi And thank you for your message, unfortunately, I didn't have much time over the last year to take charge of following up on this repo. Let me apologize about that. Did you eventually dort it out?

**Comment by joanmarticarreras** [comment]
Hi no it was not possible to launch it together with our apache site, the other sites were interfering. At the we opted for another way.

Thanks anyway.

JMC
